bosun-simple-app:
  bosun:
    name: "cheatsheet"
    team: "technicalsuccess"
    gitrepo: "what-to-do-app-front"
    fullnameOverride: ""
    buildFQDN: true

  container:
    repository: "549050352176.dkr.ecr.us-east-1.amazonaws.com/what-to-do-app-front"
    tag: "0.0.6"
    replicaCount: 2
    port: 80
    # env:
    # - name:
    #   value:
    pullPolicy: Always
    pullSecrets: []
    podAnnotations:
      # iam.amazonaws.com/role: arn:aws:iam::<AWS Account Id>:role/pods_will_use_for_AWS_access
      # prometheus.io/path: /prometheus-metrics
      # prometheus.io/port: "8081"
      prometheus.io/scrape: "false"
    volumes:
      - name: tmp
        emptyDir: {}
    volumeMounts:
      - name: tmp
        mountPath: /tmp
    livenessDelay: 400
    livenessProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 10
    readinessProbe:
      httpGet:
        port: 80
        path: /
    healthCheck: /
    healthCheckPort: 80

  serviceAccount:
    create: true
    privileged: false
    writablefs: true
    name: "cheatsheet"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: enabled
    class: private
    tlsIssuer: letsencrypt-environment-subdomain
    host: "cheatsheet"
    path: /
    annotations: {}

  resources:
    limits:
      cpu: 200m
      memory: 750Mi
    requests:
      cpu: 100m
      memory: 240Mi

  podSecurityContext:
    {}
    # runAsUser: 1001
    # runAsGroup: 1001
    # fsGroup: 1001

  nodeSelector: {}

  tolerations: []

  affinity: {}
